// definitions.js - WHAT the financial items mean.
//
// One flat lookup table keyed by datapoint code
// (the same code used next to each item in taxonomyData.js):
//   Revenue: "Income generated from the company's ordinary business activities..."
//
// How to ADD or EDIT a definition:
//   1. Use the exact datapoint code as the key.
//   2. Keep it to 1-2 short sentences written for a financial analyst.
//   3. Describe the item itself (an aggregate gets the aggregate meaning,
//      a component gets the component meaning).
// A code with no entry here shows "Definition not available." in the detail panel.
const DEFINITIONS = {
  Total_Assets: "Total resources controlled by the company, equal to total liabilities plus equity.",
  Current_Assets: "Assets expected to convert to cash or be used within one year.",
  Cash_And_Cash_Equivalents: "Cash and highly liquid investments with original maturities of three months or less.",
  Accounts_Receivable: "Amounts owed to the company by customers for goods or services already provided.",
  Inventory: "Goods held for sale or used in production, not yet sold.",
  Other_Current_Assets: "Other short-term assets not classified elsewhere.",
  Non_Current_Assets: "Long-term assets not expected to convert to cash within one year.",
  Property_Plant_Equipment: "Tangible long-lived assets such as land, buildings, and machinery.",
  Intangible_Assets: "Non-physical long-term assets such as goodwill, patents, software, and brand rights.",
  Goodwill: "Premium paid over fair value of net assets in an acquisition.",
  Other_Intangible_Assets: "Intangible assets other than goodwill.",
  Other_Non_Current_Assets: "Other long-term assets not classified elsewhere.",
  Total_Liabilities_And_Equity: "Total claims on assets, equal to total liabilities plus total equity.",
  Total_Liabilities: "Total amounts the company owes to creditors and other counterparties.",
  Current_Liabilities: "Obligations due within one year.",
  Accounts_Payable: "Amounts owed to suppliers for goods or services received.",
  Short_Term_Debt: "Borrowings and debt due within one year.",
  Other_Current_Liabilities: "Other short-term obligations not classified elsewhere.",
  Non_Current_Liabilities: "Obligations due after more than one year.",
  Long_Term_Debt: "Borrowings and debt due after more than one year.",
  Deferred_Tax_Liabilities: "Taxes owed in future periods due to temporary timing differences.",
  Other_Non_Current_Liabilities: "Other long-term obligations not classified elsewhere.",
  Total_Equity: "Residual owners' claim on assets after deducting liabilities.",
  Share_Capital: "Capital raised from shareholders through issued shares.",
  Retained_Earnings: "Cumulative profits retained in the business after dividends.",
  Other_Equity: "Other equity components such as reserves and other comprehensive income.",
  Revenue: "Income generated from the company's ordinary business activities during the period.",
  Product_Service_Revenue: "Revenue specifically attributable to products sold or services rendered.",
  Other_Operating_Revenue: "Other revenue from ordinary operations not from core products or services.",
  Cost_Of_Sales: "Total direct costs of goods sold and services delivered during the period.",
  Cost_Of_Goods_Sold: "Direct costs attributable to producing the goods or services sold during the period.",
  Other_Cost_Of_Sales: "Other direct costs of sales not captured in cost of goods sold.",
  Gross_Profit: "Revenue minus cost of sales.",
  Operating_Expenses: "Costs of running core operations, excluding cost of sales.",
  Selling_General_Administrative: "Sales, marketing, and administrative overhead costs.",
  Research_And_Development: "Spending on research and development of new products or processes.",
  Other_Operating_Expenses: "Other operating costs not classified elsewhere.",
  EBITDA: "Earnings before interest, taxes, depreciation and amortization.",
  Depreciation_And_Amortization: "Non-cash charges spreading asset costs over their useful lives.",
  EBIT: "Earnings before interest and taxes; operating profit including depreciation and amortization.",
  Non_Operating_Income_Expense: "Net gains or losses from activities outside core operations.",
  Interest_Income: "Interest earned on cash, loans, and investments during the period.",
  Interest_Expense: "Cost of borrowings incurred during the period.",
  Other_Non_Operating_Income_Expense: "Other non-operating gains or losses not classified elsewhere.",
  Profit_Before_Tax: "Profit after all operating and non-operating items but before income tax.",
  Income_Tax: "Tax expense on the period's profit, comprising current and deferred tax.",
  Net_Profit: "Profit attributable to shareholders after all expenses and taxes.",
  Net_Income: "Profit for the period, taken as the starting point of the operating cash flow reconciliation.",
  Changes_In_Working_Capital: "Cash impact of changes in short-term operating assets and liabilities.",
  Other_Operating_Adjustments: "Other non-cash and operating adjustments to reconcile cash from operations.",
  Cash_Flow_From_Operations: "Net cash generated from core operating activities.",
  Cash_Flow_From_Investing: "Net cash used in or generated from investing activities.",
  Cash_Flow_From_Financing: "Net cash from financing activities such as debt and equity.",
  Capital_Expenditure: "Cash spent on long-term physical assets.",
  Acquisitions: "Cash spent acquiring other businesses or assets.",
  Investments: "Cash paid for, or received from, purchases, sales and maturities of investments.",
  Other_Investing_Activities: "Other investing cash flows not classified elsewhere.",
  Debt_Issuance: "Cash received from issuing debt.",
  Debt_Repayment: "Cash paid to repay debt.",
  Share_Issuance: "Cash received from issuing shares.",
  Share_Buybacks: "Cash spent repurchasing the company's own shares.",
  Dividends: "Cash dividends paid to shareholders.",
  Other_Financing_Activities: "Other financing cash flows not classified elsewhere.",
  Net_Change_In_Cash: "Net increase or decrease in cash during the period.",
  Cash_And_Cash_Equivalents_At_Beginning: "Cash balance at the start of the period.",
  Cash_And_Cash_Equivalents_At_End: "Cash balance at the end of the period.",
  Bank_Total_Assets: "Total resources controlled by the bank, equal to total liabilities plus equity.",
  Cash_Balances_Central_Banks: "Cash and balances held with central banks.",
  Loans_Advances_Banks: "Loans and advances to other banks and financial institutions.",
  Loans_Advances_Customers: "Loans and advances to customers, the bank's core earning asset.",
  Investment_Securities: "Securities held by the bank for liquidity and investment income.",
  Derivative_Financial_Assets: "Positive fair value of the bank's derivative contracts.",
  Bank_Property_Equipment: "The bank's tangible fixed assets such as branches and equipment.",
  Other_Bank_Assets: "Other bank assets not classified elsewhere.",
  Bank_Total_Liabilities_And_Equity: "Total claims on the bank's assets.",
  Bank_Total_Liabilities: "Total amounts the bank owes to depositors, lenders, and counterparties.",
  Deposits_From_Banks: "Funds the bank owes to other banks, a wholesale funding source.",
  Customer_Deposits: "Deposits from customers, the bank's core funding source.",
  Debt_Securities_Issued: "Bonds and notes issued by the bank to raise funding.",
  Derivative_Financial_Liabilities: "Negative fair value of the bank's derivative contracts.",
  Subordinated_Debt: "Lower-ranking debt that absorbs losses before senior creditors.",
  Other_Bank_Liabilities: "Other bank obligations not classified elsewhere.",
  Bank_Total_Equity: "Residual owners' claim on the bank after deducting liabilities.",
  Bank_Share_Capital: "Capital raised from the bank's shareholders through issued shares.",
  Bank_Retained_Earnings: "Cumulative bank profits retained after dividends.",
  Bank_Reserves: "Reserves and other equity components of the bank.",
  Bank_Interest_Expense: "Interest paid by the bank on deposits and borrowings.",
  Net_Interest_Income: "Interest income minus interest expense; the bank's core earnings measure.",
  Non_Interest_Income: "Bank income from fees, trading, and other non-interest sources.",
  Net_Fee_Commission_Income: "Net income from fees and commissions for banking services.",
  Trading_Fair_Value_Income: "Gains or losses from trading and fair-value instruments.",
  Bank_Other_Operating_Income: "Other bank operating income not classified elsewhere.",
  Credit_Loss_Expense: "Charge for expected and incurred losses on loans and credit exposures.",
  Loan_Loss_Provisions: "Provisions set aside against probable loan losses.",
  Credit_Impairment_Charges: "Charges for impairment of credit exposures and financial assets.",
  Staff_Expenses: "Employee compensation and benefit costs of the bank.",
  Administrative_Expenses: "Administrative and overhead costs of running the bank.",
  Bank_Taxation: "Income tax expense of the bank for the period.",
  Bank_CF_Operating_Profit: "Bank operating profit before tax as the cash flow starting point.",
  Bank_CF_Non_Cash_Adjustments: "Non-cash adjustments to reconcile bank operating profit to cash.",
  Bank_CF_Change_In_Loans: "Cash impact of changes in loans and advances.",
  Bank_CF_Change_In_Deposits: "Cash impact of changes in customer deposits.",
  Bank_CF_Investment_Securities_Purchase: "Cash spent purchasing investment securities.",
  Bank_CF_Investment_Securities_Proceeds: "Cash received from sale or maturity of investment securities.",
  Bank_CF_Capex: "Cash spent on the bank's fixed assets.",
  Bank_CF_Subordinated_Debt_Issued: "Cash received from issuing subordinated debt.",
  Bank_CF_Subordinated_Debt_Repaid: "Cash paid to repay subordinated debt.",
  Bank_CF_Dividends_Paid: "Cash dividends paid by the bank to shareholders.",
  EPS: "Net profit divided by weighted average shares outstanding.",
  Diluted_EPS: "Net profit divided by shares including potential dilutive securities.",
  DPS: "Dividend declared per ordinary share.",
  Book_Value_Per_Share: "Total equity divided by shares outstanding.",
  Tangible_Book_Value_Per_Share: "Tangible equity divided by shares outstanding.",
  Weighted_Average_Shares_Outstanding: "Average shares outstanding during the period, adjusted for timing.",
  Diluted_Weighted_Average_Shares_Outstanding: "Average shares including potential dilutive securities.",
  Dividend_Payout: "Share of earnings distributed as dividends."
};

// Lets Node load this file for quick checks (ignored by the browser).
if (typeof module !== "undefined" && module.exports) {
  module.exports = { DEFINITIONS };
}
